name: Daily issue
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
jobs:
  create_issue:
    name: Create daily task issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create daily task issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
            --label "${LABELS}" \
            --json number \
            --jq '.[0].number')
            if [[ -n $preious_issue_number ]]; then
              gh issue close "$preious_issue_number"
              gh issue unpin "$preious_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "Daily note - $(date +%Y-%m-%d)" \
            --label "${LABELS}" \
            --body "${BODY}")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          LABELS: diary
          TZ: 'Asia/Tokyo'
          BODY: |
            ### Agenda

            - [ ] Note anything I did today

            ### Articles I read today
            - [ ] Link 1
            - [ ] Link 2
          PINNED: false
          CLOSE_PREVIOUS: false
